/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type StreamOptions struct {

	IncludeUsage *bool `json:"include_usage,omitempty"`

	ContinuousUsageStats *bool `json:"continuous_usage_stats,omitempty"`
}
