/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChatCompletionUserMessageParam struct {

	Content Content `json:"content"`

	Role string `json:"role"`

	Name string `json:"name,omitempty"`
}
