/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChatCompletionContentPartImageParam struct {

	ImageUrl ImageUrl `json:"image_url"`

	Type string `json:"type"`
}
