/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ValidationError struct {

	Loc []ValidationErrorLocInner `json:"loc"`

	Msg string `json:"msg"`

	Type string `json:"type"`
}
