/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FunctionDefinition struct {

	Name string `json:"name"`

	Description *string `json:"description,omitempty"`

	Parameters *map[string]interface{} `json:"parameters,omitempty"`
}
