/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EmbeddingRequest struct {

	Input Input `json:"input"`

	EncodingFormat *string `json:"encoding_format,omitempty" validate:"regexp=^(float|base64)$"`

	Model *string `json:"model,omitempty"`

	Dimensions *int32 `json:"dimensions,omitempty"`

	User *string `json:"user,omitempty"`
}
