/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GuidedWhitespacePattern - If specified, will override the default whitespace pattern for guided json decoding.
type GuidedWhitespacePattern struct {
}
