/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CompletionRequest struct {

	Prompt Prompt `json:"prompt"`

	Model Model `json:"model,omitempty"`

	BestOf BestOf `json:"best_of,omitempty"`

	Echo Echo `json:"echo,omitempty"`

	FrequencyPenalty FrequencyPenalty `json:"frequency_penalty,omitempty"`

	LogitBias LogitBias `json:"logit_bias,omitempty"`

	Logprobs Logprobs1 `json:"logprobs,omitempty"`

	MaxTokens MaxTokens1 `json:"max_tokens,omitempty"`

	N int32 `json:"n,omitempty"`

	PresencePenalty PresencePenalty `json:"presence_penalty,omitempty"`

	Seed Seed `json:"seed,omitempty"`

	Stop Stop `json:"stop,omitempty"`

	Stream Stream `json:"stream,omitempty"`

	StreamOptions ChatCompletionRequestStreamOptions `json:"stream_options,omitempty"`

	Suffix Suffix `json:"suffix,omitempty"`

	Temperature Temperature1 `json:"temperature,omitempty"`

	TopP TopP `json:"top_p,omitempty"`

	User User `json:"user,omitempty"`

	UseBeamSearch bool `json:"use_beam_search,omitempty"`

	TopK int32 `json:"top_k,omitempty"`

	MinP float32 `json:"min_p,omitempty"`

	RepetitionPenalty float32 `json:"repetition_penalty,omitempty"`

	LengthPenalty float32 `json:"length_penalty,omitempty"`

	EarlyStopping bool `json:"early_stopping,omitempty"`

	StopTokenIds StopTokenIds `json:"stop_token_ids,omitempty"`

	IncludeStopStrInOutput bool `json:"include_stop_str_in_output,omitempty"`

	IgnoreEos bool `json:"ignore_eos,omitempty"`

	MinTokens int32 `json:"min_tokens,omitempty"`

	SkipSpecialTokens bool `json:"skip_special_tokens,omitempty"`

	SpacesBetweenSpecialTokens bool `json:"spaces_between_special_tokens,omitempty"`

	TruncatePromptTokens TruncatePromptTokens `json:"truncate_prompt_tokens,omitempty"`

	AllowedTokenIds AllowedTokenIds `json:"allowed_token_ids,omitempty"`

	// If true (the default), special tokens (e.g. BOS) will be added to the prompt.
	AddSpecialTokens bool `json:"add_special_tokens,omitempty"`

	ResponseFormat CompletionRequestResponseFormat `json:"response_format,omitempty"`

	GuidedJson GuidedJson `json:"guided_json,omitempty"`

	GuidedRegex GuidedRegex `json:"guided_regex,omitempty"`

	GuidedChoice GuidedChoice `json:"guided_choice,omitempty"`

	GuidedGrammar GuidedGrammar `json:"guided_grammar,omitempty"`

	GuidedDecodingBackend GuidedDecodingBackend1 `json:"guided_decoding_backend,omitempty"`

	GuidedWhitespacePattern GuidedWhitespacePattern `json:"guided_whitespace_pattern,omitempty"`
}
