/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ContentAnyOfInner struct {

	Text string `json:"text"`

	Type string `json:"type"`

	ImageUrl ImageUrl `json:"image_url"`
}
