/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MessagesInner struct {

	Content string `json:"content"`

	Role string `json:"role"`

	Name string `json:"name"`

	FunctionCall FunctionCall `json:"function_call,omitempty"`

	ToolCalls []ChatCompletionMessageToolCallParam `json:"tool_calls,omitempty"`

	ToolCallId string `json:"tool_call_id"`
}
