/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChatCompletionFunctionMessageParam struct {

	Content *string `json:"content"`

	Name string `json:"name"`

	Role string `json:"role"`
}
