/*
 * OpenAI API Reference Server
 *
 * This is an API reference server that mimics openai server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ChatTemplate - A Jinja template to use for this conversion. If this is not passed, the model's default chat template will be used instead.
type ChatTemplate struct {
}
